a = [
    {
        "name": "2PLT",
        "roles": [],
        "id": "867133537442594867",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "1PLT",
        "roles": [],
        "id": "867133537755987978",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "B1",
        "roles": [],
        "id": "867133537894137867",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "A1",
        "roles": [],
        "id": "867133537919696896",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "A2",
        "roles": [],
        "id": "867133537952727071",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "ASL",
        "roles": [],
        "id": "867133538167947264",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "C2",
        "roles": [],
        "id": "867133538382118942",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "B2",
        "roles": [],
        "id": "867133538398502912",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "C1",
        "roles": [],
        "id": "867133538527608832",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "CSL",
        "roles": [],
        "id": "867133538570993666",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "CO",
        "roles": [],
        "id": "867133538582265936",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "E1",
        "roles": [],
        "id": "867133538725658734",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "G1",
        "roles": [],
        "id": "867133538746368001",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "GSL",
        "roles": [],
        "id": "867133538763800578",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "D1",
        "roles": [],
        "id": "867133538783723561",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "DSL",
        "roles": [],
        "id": "867133538831040533",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "F1",
        "roles": [],
        "id": "867133538913746974",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "ESL",
        "roles": [],
        "id": "867133538935373864",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "FAC",
        "roles": [],
        "id": "867133538939174958",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "FSL",
        "roles": [],
        "id": "867133538993307689",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "H1",
        "roles": [],
        "id": "867133539010609153",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "HQ",
        "roles": [],
        "id": "867133539034988594",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "BSL",
        "roles": [],
        "id": "867133541564547072",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
    {
        "name": "Blue",
        "roles": [],
        "id": "890342348779831296",
        "require_colons": True,
        "managed": False,
        "animated": False,
        "available": True,
    },
]
